spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tuquangnhat_21107601
#    host: localhost
#    port: 5432
    username: postgres
    password: 12345
#    database-name: tuquangnhat_21107601
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect